name: CI/CD

on:
  push:
    branches:
     - "*"
    tags:
     - "*"
  pull_request:

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1.2.0

    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: Get the Docker Tag
      run: echo "${GITHUB_REF##*/}"

    - name: Extract tag name
      shell: bash
      run: echo "##[set-output name=imagetag;]$(echo ${GITHUB_REF##*/})"
      id: extract_tag_name

    - name: Build Uproot Image
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: bengal1/servicex_code_gen_func_adl_uproot:${{ steps.extract_tag_name.outputs.imagetag }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
