name: CI/CD

on:
  push:
    branches:
     - "*"
    tags:
     - "*"
  pull_request:

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1.2.0

    - name: Build Uproot Image
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: bengal1/servicex_code_gen_func_adl_uproot
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tag: "${GITHUB_REF##*/}"
