name: CI/CD

on:
  push:
    branches:
     - "*"
    tags:
     - "*"
  pull_request:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Build Uproot Image
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: bengal1/servicex_code_gen_func_adl_uproot
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tag: "${GITHUB_REF##*/}"

